export { createBookAggregate } from './book/index.js';
export type { BookAggregateDeps } from './book/index.js';
export { createOutlineAggregate } from './outline/index.js';
export type { OutlineAggregateDeps } from './outline/index.js';
export { createChapterAggregate } from './chapter/index.js';
export type { ChapterAggregateDeps } from './chapter/index.js';
export { createNarrativeWorldAggregate } from './narrative-world/index.js';
export type { NarrativeWorldDeps } from './narrative-world/index.js';
export { createContinuityAggregate } from './continuity/index.js';
export type { ContinuityAggregateDeps, ChapterContinuityUpdate } from './continuity/index.js';
