import type { StorySkill } from './types.js';

export const storySkillRegistry: StorySkill[] = [
  {
    id: 'story-structure',
    name: '大纲排布',
    type: 'process',
    priority: 100,
    rigidity: 'hard',
    triggers: ['write_chapter', 'revise_chapter', 'audit_story'],
    requiredContext: ['volumePlans', 'narrativeThreads'],
    promptRules: [
      '本章必须服务当前卷计划。',
      '本章必须产生可描述的剧情位移。',
      '主线不能连续停滞。',
    ],
    auditQuestions: ['本章是否服务当前卷计划？', '主线是否发生可描述位移？'],
    redFlags: ['主线多章没有推进。'],
  },
  {
    id: 'chapter-goal',
    name: '当前章目标',
    type: 'process',
    priority: 95,
    rigidity: 'hard',
    triggers: ['write_chapter', 'revise_chapter'],
    requiredContext: ['chapterCard'],
    promptRules: [
      '必须完成章节卡 mustChange。',
      '必须体现章节卡 plotFunction。',
      '结尾必须承接或强化章节卡 endingHook。',
    ],
    auditQuestions: ['是否完成 mustChange？', '是否强化 endingHook？'],
    redFlags: ['章节结尾只是总结，没有下一步压力。'],
  },
  {
    id: 'character-logic',
    name: '人物动机',
    type: 'process',
    priority: 90,
    rigidity: 'hard',
    triggers: ['write_chapter', 'revise_chapter', 'design_character', 'audit_story'],
    requiredContext: ['characterArcs', 'relationshipEdges'],
    promptRules: [
      '人物行动必须能从欲望、恐惧、缺陷、误信或当前压力中解释。',
      '不允许为了推动剧情让人物突然降智或突然变聪明。',
      '不能越过 lineWillNotCross，除非本章明确写出代价和转折原因。',
    ],
    auditQuestions: ['人物行动是否符合既有动机？', '是否出现 OOC 或剧情服务式降智？'],
    redFlags: ['人物为了剧情服务而失真。', '反派或配角不合理降智。'],
  },
  {
    id: 'emotion-curve',
    name: '情绪曲线',
    type: 'process',
    priority: 80,
    rigidity: 'soft',
    triggers: ['write_chapter', 'revise_chapter', 'design_opening'],
    requiredContext: ['targetReaderExperience'],
    promptRules: [
      '本章需要有可感知的情绪方向。',
      '情绪变化应由事件、选择或关系动作触发。',
      '不能用解释性独白代替情绪推进。',
    ],
    auditQuestions: ['情绪变化是否由场景动作触发？'],
    redFlags: ['只标注情绪，没有可见行动或代价。'],
  },
  {
    id: 'opening-hook',
    name: '开头设计',
    type: 'execution',
    priority: 75,
    rigidity: 'soft',
    triggers: ['write_chapter', 'design_opening'],
    requiredContext: ['previousChapterEnding'],
    promptRules: [
      '开头尽快给出异常、冲突、欲望、危险或未解问题。',
      '不用大段背景解释开局。',
      '前几段必须建立读者继续阅读的理由。',
    ],
    auditQuestions: ['开头是否快速建立阅读理由？'],
    redFlags: ['开头用大段背景解释卸掉张力。'],
  },
  {
    id: 'hook-technique',
    name: '钩子技法',
    type: 'execution',
    priority: 70,
    rigidity: 'soft',
    triggers: ['write_chapter', 'revise_chapter', 'design_opening'],
    requiredContext: ['chapterCard', 'tensionBudget'],
    promptRules: [
      '章节结尾必须制造下一章必须承接的问题。',
      '信息揭示后要留下新的不确定性。',
      '冲突可以阶段性解决，但不能完全卸力。',
    ],
    auditQuestions: ['结尾是否有明确追读压力？', '是否留下未完成问题？'],
    redFlags: ['冲突在章末完全解决。', '读者没有下一步问题。'],
  },
  {
    id: 'dialogue-control',
    name: '对话技法',
    type: 'execution',
    priority: 65,
    rigidity: 'soft',
    triggers: ['write_chapter', 'revise_chapter', 'de_ai'],
    requiredContext: ['relationshipEdges'],
    promptRules: [
      '对话必须带有目的、遮掩、试探、冲突或关系变化。',
      '不用对白整块解释设定。',
      '角色说话方式应符合身份、关系和当下压力。',
    ],
    auditQuestions: ['对白是否只在解释设定？'],
    redFlags: ['对话只在解释设定。'],
  },
  {
    id: 'genre-pattern',
    name: '题材框架',
    type: 'execution',
    priority: 60,
    rigidity: 'hard',
    triggers: ['write_chapter', 'design_opening', 'audit_story'],
    requiredContext: ['genreContract', 'targetReaderExperience'],
    promptRules: [
      '本章需要回应 genreContract。',
      '读者回报必须符合题材预期。',
      '不能为了技巧破坏目标读者体验。',
    ],
    auditQuestions: ['本章是否兑现题材承诺？'],
    redFlags: ['技巧压过目标读者体验。'],
  },
  {
    id: 'prose-style',
    name: '风格模块',
    type: 'execution',
    priority: 50,
    rigidity: 'soft',
    triggers: ['write_chapter', 'revise_chapter', 'de_ai'],
    requiredContext: ['voiceGuide'],
    promptRules: [
      '遵守 voiceGuide。',
      '镜头、心理、动作和叙述密度要匹配当前场景。',
      '文风优化不能改变事实、关系和人物动机。',
    ],
    auditQuestions: ['文风是否改变了事实或人物动机？'],
    redFlags: ['漂亮句子覆盖了真实行动。'],
  },
  {
    id: 'de-ai-style',
    name: '去 AI 味',
    type: 'execution',
    priority: 45,
    rigidity: 'soft',
    triggers: ['revise_chapter', 'de_ai'],
    requiredContext: ['voiceGuide'],
    promptRules: [
      '删除泛泛总结和抽象情绪标签。',
      '用具体动作、选择、物件、环境反馈呈现心理。',
      '避免连续使用同构句式和套路化转场。',
    ],
    auditQuestions: ['是否存在模板化总结和抽象情绪标签？'],
    redFlags: ['连续使用同构句式和套路化转场。'],
  },
  {
    id: 'consistency-audit',
    name: '一致性检查',
    type: 'audit',
    priority: 40,
    rigidity: 'hard',
    triggers: ['write_chapter', 'revise_chapter', 'audit_story'],
    requiredContext: ['narrativeBible', 'worldRules'],
    promptRules: [],
    auditQuestions: [
      '是否违反世界规则？',
      '是否改变已建立人物逻辑？',
      '是否新增未授权的重要设定？',
    ],
    redFlags: ['新增未授权的重要设定。'],
  },
  {
    id: 'pacing-audit',
    name: '节奏检查',
    type: 'audit',
    priority: 35,
    rigidity: 'hard',
    triggers: ['write_chapter', 'revise_chapter', 'audit_story'],
    requiredContext: ['chapterCard', 'tensionBudget'],
    promptRules: [],
    auditQuestions: [
      '是否有剧情位移？',
      '是否有选择压力？',
      '是否有代价或后果？',
      '是否重复相同张力模式？',
    ],
    redFlags: ['伏笔只埋不推。', '爽点缺少压抑、代价或关系变化支撑。'],
  },
  {
    id: 'red-flag-audit',
    name: '红旗检查',
    type: 'audit',
    priority: 30,
    rigidity: 'hard',
    triggers: ['write_chapter', 'revise_chapter', 'audit_story', 'de_ai'],
    requiredContext: ['chapterCard', 'narrativeBible'],
    promptRules: [],
    auditQuestions: [
      '人物是否为了剧情服务而失真？',
      '对话是否只在解释设定？',
      '章末是否没有追读压力？',
    ],
    redFlags: [
      '人物为了剧情服务而失真。',
      '反派或配角不合理降智。',
      '对话只在解释设定。',
      '章末没有追读压力。',
    ],
  },
];
